---
title: "characterBindingFactorVectorWarningDebug"
author: "Alex Holcombe"
output: html_document
---
use_dev_version() increments the version, after commits made

### Places where I mess with warnings

* The problem can also arise perhaps in analyzeOneCondition.R line 96

* Also fit_model.R line 48 is what replaces NULL warnings with None, which I had to do to avoid stuff being set to NULL and thus getting deleted.

* analyze_one_condition.R line 96

### only issue remaining?

binding character and factor vector, coercing into character vector

### warning binding error, fixed



At end when all getting bound together,

Error in bind_rows_(x, .id) : 
  Column `warnings` can't be converted from character to list
  
  All upper - lower must be >= 2*rhobeg. Changing rhobeg

Victory declared! The below now runs without error.

```{r}

library(mixRSVP)
data <- backwards2_E1 #A dataset provided as an example with the package
#.mat file been preprocessed into melted long dataframe
numItemsInStream <- length( data$letterSeq[1,] )  
library(dplyr)

#To use dplyr operations, each column must be a 1d atomic vector or a list. So, can't have array fields like letterSeq
data$letterSeq<- NULL

#Give conditions better names than 1 and 2
names(data)[names(data) == 'target'] <- 'stream'
data <- data %>% mutate( stream =ifelse(stream==1, "Left","Right") )
#mutate condition to Orientation
names(data)[names(data) == 'condition'] <- 'orientation'
data <- data %>% mutate( orientation =ifelse(orientation==1, "Canonical","Inverted") )

condtnVariableNames <- c("subject","orientation", "stream") # 
minSPE<- -17; maxSPE<- 17

df<- data %>% dplyr::filter(subject>="AE",subject<="AG") #Includes one or two who fail the likelihood ratio test, for illustration

curves<- df %>% group_by_at(.vars = condtnVariableNames) %>% 
  do(calc_curves_dataframe(.,minSPE,maxSPE,numItemsInStream))


```

> "assigning warning from estimate None which is type  character"
Tells me that sometimes the warning is None, represented as type character

> "assigning warning from estimatelist(message = \"NaNs produced\", call = pnorm(binStart + binWidth, latency, precision))which is type list"

Also printed as:
> [[1]] <simpleWarning in pnorm(binStart + binWidth, latency, precision): NaNs produced>

Its structure is:
```
List of 1
 $ :List of 2
  ..$ message: chr "NaNs produced"
  ..$ call   : language pnorm(binStart + binWidth, latency, precision)
  ..- attr(*, "class")= chr [1:3] "simpleWarning" "warning" "condition"
```

So, I have amended calc_curves_dataframe to turn all that into a string.
The call is a structure of type language and I need to find out who formats it so I can turn it into normal long string

ww[[1]]$call

x<- ww[[1]]$message

y<- capture.output(
      print( ww[[1]]$call )
    )
paste0("message= ",x,", call= ",y)

    

