---
title: "Do-it-yourself histogram and curvefit plotting"
author: "Alex Holcombe"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
      fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Do-it-yourself histogram and curvefit plotting}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The below can alternatively all be done with the plotHistWithFit function.

```{r, fig.show='hold', fig.cap = "Fitted guessing distribution in yellow, gaussian in light blue, combined in green"}

#in the future need to move this data maybe from tests directory because meant to be only for tests
data <- backwards2_E1 #.mat file been preprocessed into melted long dataframe

library(dplyr)
numItemsInStream<- length( data$letterSeq[1,] )  
#It seems that to work with dplyr, can't have array field like letterSeq
data$letterSeq<- NULL

#plot histogram
require(ggplot2)
minSPE<- -17; maxSPE<- 17

#Give conditions better names than 1 and 2
names(data)[names(data) == 'target'] <- 'stream'
data <- data %>% mutate( stream =ifelse(stream==1, "Left","Right") )
#mutate condition to Orientation
names(data)[names(data) == 'condition'] <- 'orientation'
data <- data %>% mutate( orientation =ifelse(orientation==1, "Canonical","Inverted") )

#Test on one subject
df<-data %>% dplyr::filter(subject=="BE")

library(mixRSVP)
#Accomplish same as plotHistWithFit functionality
curveDfs<- calc_curves_dataframes(df,minSPE,maxSPE,numItemsInStream)

g=ggplot(df, aes(x=SPE)) + theme_apa()
#plot data
g<-g+geom_histogram(binwidth=1) + xlim(minSPE,maxSPE)
g<-g+ geom_line(data=curveDfs,aes(x=x,y=guessingFreq),color="yellow",size=1.2)

h<-g+ geom_line(data=curveDfs,aes(x=x,y=gaussianFreq),color="lightblue",size=1.2)
h<-h+ geom_point(data=curveDfs,aes(x=x,y=combinedFitFreq),color="green",size=1.2)
h
#Alternatively plot finer-grained (finer than histogram bins) theoretical Gaussian, in dark blue.

#   estimates<- analyzeOneCondition(df,numItemsInStream,parameterBounds())
efficacy<- curveDfs$efficacy[1]; latency<- curveDfs$latency[1]; precision<- curveDfs$precision[1]
grain<-.05
numObservations<- length(df$SPE)
#Scale up the numObservations to compensate for the smaller grain size
numObservations<- numObservations
gaussianThis<- gaussian_scaled(efficacy,latency,precision,numObservations,minSPE,maxSPE,grain) 
g<-g + geom_line(data=gaussianThis,aes(x=x,y=gaussianFreq),color="darkblue",size=1.2)
g
```

#Alternatively plot finer-grained (finer than histogram bins) theoretical Gaussian, in dark blue.

```{r, fig.show='hold', fig.cap = "Fitted guessing distribution in yellow, gaussian in light blue, combined in green"}



```

